// <auto-generated />
using System;
using ECommerce.DataAccess.Concrete.EfCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ECommerce.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Entities.Concrete.Ad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdDate")
                        .HasColumnType("date");

                    b.Property<string>("AdDetail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("AdFromWho")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AdSwapStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<decimal>("AdVehiclePrice")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("AdVehicleStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DamageStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Ads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdDate = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(5756),
                            AdDetail = "ÇOK GÜZEL ARABA",
                            AdFromWho = "ByOwner",
                            AdNo = "123456789",
                            AdSwapStatus = "Yes",
                            AdTitle = "Sahibinden Tertemiz Araba",
                            AdVehiclePrice = 350000.50m,
                            AdVehicleStatus = "FirstHand",
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(5738),
                            DamageStatus = "Unspecified",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(5745)
                        },
                        new
                        {
                            Id = 2,
                            AdDate = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(5763),
                            AdDetail = "ÇOK GÜZEL ARABA",
                            AdFromWho = "ByOwner",
                            AdNo = "234567891",
                            AdSwapStatus = "No",
                            AdTitle = "Sahibinden Boyasız Araba",
                            AdVehiclePrice = 150000.7840m,
                            AdVehicleStatus = "SecondHand",
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(5760),
                            DamageStatus = "HeavilyDamaged",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(5761)
                        },
                        new
                        {
                            Id = 3,
                            AdDate = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(5768),
                            AdDetail = "ÇOK GÜZEL ARABA",
                            AdFromWho = "FromAuthorizedDealer",
                            AdNo = "345678912",
                            AdSwapStatus = "Yes",
                            AdTitle = "İTHAL ARAÇ",
                            AdVehiclePrice = 1000000.50m,
                            AdVehicleStatus = "ImportedFirstHand",
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(5765),
                            DamageStatus = "Unspecified",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(5766)
                        },
                        new
                        {
                            Id = 4,
                            AdDate = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(5774),
                            AdDetail = "ÇOK GÜZEL ARABA",
                            AdFromWho = "FromTheGalery",
                            AdNo = "456789123",
                            AdSwapStatus = "No",
                            AdTitle = "Galeriden Temiz Araç",
                            AdVehiclePrice = 2500000.80m,
                            AdVehicleStatus = "FirstHand",
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(5771),
                            DamageStatus = "WithoutDamageRegistration",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(5772)
                        });
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressDetails")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AddressTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DefaultAddress")
                        .HasColumnType("boolean");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NeighborhoodOrVillage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressDetails = "Naci Bekir Mahallesi ,Atılım Cad. Ateş Sok. No:40/7 06500 Yenimahalle/Ankara/Türkiye",
                            AddressTitle = "Evim",
                            AddressType = "Home",
                            City = "Ankara",
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 230, DateTimeKind.Local).AddTicks(4570),
                            DefaultAddress = false,
                            District = "Yenimahalle",
                            Email = "bolatcan@email.com",
                            FirstName = "ibo",
                            IsActive = false,
                            IsDeleted = false,
                            LastName = "BOL",
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 230, DateTimeKind.Local).AddTicks(4577),
                            NeighborhoodOrVillage = "Naci Bekir",
                            PhoneNumber = "+90(532)5757966",
                            PostalCode = "06500",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddressDetails = "Mustafa Kemal Mahallesi ,Eskişehir Yolu  Kütahya Sok. No:280/7 06500 Çankaya/Ankara/Türkiye",
                            AddressTitle = "İş",
                            AddressType = "Work",
                            City = "Ankara",
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 230, DateTimeKind.Local).AddTicks(4590),
                            DefaultAddress = true,
                            District = "Çankaya",
                            Email = "bolatcan@email.com",
                            FirstName = "ibo",
                            IsActive = false,
                            IsDeleted = false,
                            LastName = "BOLAT",
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 230, DateTimeKind.Local).AddTicks(4591),
                            NeighborhoodOrVillage = "Mustafa Kemal",
                            PhoneNumber = "+90(532)5757966",
                            PostalCode = "06100",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(8143),
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(8149),
                            Name = "Wolkswagen",
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(8157),
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(8158),
                            Name = "Honda",
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(8160),
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(8161),
                            Name = "Fiat",
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(8163),
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(8164),
                            Name = "Nissan",
                            SubCategoryId = 4
                        });
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.Identity.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "7a8ebbbe-f7f3-4205-8082-b424819283b3",
                            CreatedByName = "Owner",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 224, DateTimeKind.Local).AddTicks(7259),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "Owner",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 224, DateTimeKind.Local).AddTicks(7282),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.Identity.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GenderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserIdendityNo")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aad43044-3017-4a24-b31f-b5a66428b20b",
                            CreatedByName = "Owner",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 225, DateTimeKind.Local).AddTicks(2573),
                            Email = "bolat6606@hotmail.com",
                            EmailConfirmed = true,
                            FirstName = "İbrahim",
                            GenderType = "Unspecified",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Bolat",
                            LockoutEnabled = false,
                            ModifiedByName = "Owner",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 225, DateTimeKind.Local).AddTicks(2580),
                            NormalizedEmail = "BOLAT6606@HOTMAIL.COM",
                            NormalizedUserName = "BOLAT6606",
                            PasswordHash = "AQAAAAEAACcQAAAAEMw7P7WAEhOmhvBP5pbrl2cGycZhfnw/6/oHevpQYWTwYloUpVG97llOcTd5f6UIgw==",
                            PhoneNumber = "+90(532)575-79-66",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "VVPCRDAS3MJWQD5CSW2GWPRADBXEZINA",
                            TwoFactorEnabled = false,
                            UserName = "bolat6606"
                        });
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.MainCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("MainCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(9509),
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(9515),
                            Name = "Araçlar"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(9524),
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 232, DateTimeKind.Local).AddTicks(9525),
                            Name = "Yedek Parçalar"
                        });
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("BodyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EngineCapacity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnginePower")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EquipmentVariant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GearType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuaranteeStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kilometer")
                        .HasColumnType("integer");

                    b.Property<string>("ModelColour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModelYear")
                        .HasMaxLength(4)
                        .HasColumnType("integer")
                        .IsFixedLength();

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PlateNationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TractionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyType = "Hatchback5Door",
                            BrandId = 1,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(3696),
                            EngineCapacity = "Cm13011600",
                            EnginePower = "Hp101125",
                            EngineType = "1.6 TDI",
                            EquipmentVariant = "Confortline",
                            FuelType = "Diesel",
                            GearType = "Automatic",
                            GuaranteeStatus = "No",
                            IsActive = false,
                            IsDeleted = false,
                            Kilometer = 102000,
                            ModelColour = "White",
                            ModelYear = 2015,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(3702),
                            Name = "Golf",
                            PlateNationality = "TurkeyPlate",
                            TractionType = "FrontDrive"
                        },
                        new
                        {
                            Id = 2,
                            BodyType = "Hatchback5Door",
                            BrandId = 2,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(3717),
                            EngineCapacity = "Cm13011600",
                            EnginePower = "Hp101125",
                            EngineType = "1.4 TSI",
                            EquipmentVariant = "Confortline",
                            FuelType = "Diesel",
                            GearType = "Automatic",
                            GuaranteeStatus = "No",
                            IsActive = false,
                            IsDeleted = false,
                            Kilometer = 102000,
                            ModelColour = "White",
                            ModelYear = 2015,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(3718),
                            Name = "City",
                            PlateNationality = "TurkeyPlate",
                            TractionType = "FrontDrive"
                        },
                        new
                        {
                            Id = 3,
                            BodyType = "Hatchback5Door",
                            BrandId = 3,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(3723),
                            EngineCapacity = "Cm13011600",
                            EnginePower = "Hp101125",
                            EngineType = "1.6 TDI",
                            EquipmentVariant = "Confortline",
                            FuelType = "Diesel",
                            GearType = "Automatic",
                            GuaranteeStatus = "No",
                            IsActive = false,
                            IsDeleted = false,
                            Kilometer = 102000,
                            ModelColour = "White",
                            ModelYear = 2015,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(3724),
                            Name = "Egea",
                            PlateNationality = "TurkeyPlate",
                            TractionType = "FrontDrive"
                        },
                        new
                        {
                            Id = 4,
                            BodyType = "Hatchback5Door",
                            BrandId = 4,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(3728),
                            EngineCapacity = "Cm13011600",
                            EnginePower = "Hp101125",
                            EngineType = "1.6 Düz",
                            EquipmentVariant = "Confortline",
                            FuelType = "Diesel",
                            GearType = "Automatic",
                            GuaranteeStatus = "No",
                            IsActive = false,
                            IsDeleted = false,
                            Kilometer = 102000,
                            ModelColour = "White",
                            ModelYear = 2015,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(3729),
                            Name = "Qashqai",
                            PlateNationality = "TurkeyPlate",
                            TractionType = "FrontDrive"
                        });
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MainCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(697),
                            IsActive = false,
                            IsDeleted = false,
                            MainCategoryId = 1,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(703),
                            Name = "Otomobil"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(711),
                            IsActive = false,
                            IsDeleted = false,
                            MainCategoryId = 1,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(712),
                            Name = "Motorsiklet"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(714),
                            IsActive = false,
                            IsDeleted = false,
                            MainCategoryId = 1,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(715),
                            Name = "Minivan & Panelvan"
                        },
                        new
                        {
                            Id = 4,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(717),
                            IsActive = false,
                            IsDeleted = false,
                            MainCategoryId = 1,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(718),
                            Name = "Arazi, SUV & Pickup"
                        });
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.UserImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageAltText")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Profil")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 230, DateTimeKind.Local).AddTicks(5523),
                            ImageAltText = "Profil",
                            ImagePath = "/admin/images/userimages/1/profil.jpg",
                            ImageTitle = "ProfilResmi",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 230, DateTimeKind.Local).AddTicks(5528),
                            Profil = true,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.VehicleAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("AddressDetails")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AddressTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NeighborhoodOrVillage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.ToTable("VehicleAddresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressDetails = "Naci Bekir Mahallesi ,Atılım Cad. Ateş Sok. No:40/7 06500 Yenimahalle/Ankara/Türkiye",
                            AddressTitle = "Evim",
                            City = "Ankara",
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(4910),
                            District = "Yenimahalle",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(4915),
                            NeighborhoodOrVillage = "Naci Bekir",
                            PostalCode = "06500"
                        },
                        new
                        {
                            Id = 2,
                            AddressDetails = "Naci Bekir Mahallesi ,Atılım Cad. Ateş Sok. No:40/7 06500 Yenimahalle/Ankara/Türkiye",
                            AddressTitle = "Evim",
                            City = "Ankara",
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(4922),
                            District = "Yenimahalle",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(4923),
                            NeighborhoodOrVillage = "Naci Bekir",
                            PostalCode = "06500"
                        },
                        new
                        {
                            Id = 3,
                            AddressDetails = "Naci Bekir Mahallesi ,Atılım Cad. Ateş Sok. No:40/7 06500 Yenimahalle/Ankara/Türkiye",
                            AddressTitle = "Evim",
                            City = "Ankara",
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(4926),
                            District = "Yenimahalle",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(4927),
                            NeighborhoodOrVillage = "Naci Bekir",
                            PostalCode = "06500"
                        },
                        new
                        {
                            Id = 4,
                            AddressDetails = "Naci Bekir Mahallesi ,Atılım Cad. Ateş Sok. No:40/7 06500 Yenimahalle/Ankara/Türkiye",
                            AddressTitle = "Evim",
                            City = "Ankara",
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(4929),
                            District = "Yenimahalle",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(4930),
                            NeighborhoodOrVillage = "Naci Bekir",
                            PostalCode = "06500"
                        });
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.VehicleImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageAltText")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AdId");

                    b.ToTable("VehicleImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdId = 1,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(5947),
                            ImageAltText = "Profil",
                            ImagePath = "/admin/images/userimages/profil.png",
                            ImageTitle = "ProfilResmi",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(5952)
                        },
                        new
                        {
                            Id = 2,
                            AdId = 2,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(5960),
                            ImageAltText = "Profil",
                            ImagePath = "/admin/images/userimages/profil.png",
                            ImageTitle = "ProfilResmi",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(5961)
                        },
                        new
                        {
                            Id = 3,
                            AdId = 3,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(5964),
                            ImageAltText = "Profil",
                            ImagePath = "/admin/images/userimages/profil.png",
                            ImageTitle = "ProfilResmi",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(5965)
                        },
                        new
                        {
                            Id = 4,
                            AdId = 4,
                            CreatedByName = "Admin",
                            CreatedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(5967),
                            ImageAltText = "Profil",
                            ImagePath = "/admin/images/userimages/profil.png",
                            ImageTitle = "ProfilResmi",
                            IsActive = false,
                            IsDeleted = false,
                            ModifiedByName = "Admin",
                            ModifiedTime = new DateTime(2022, 10, 27, 15, 26, 26, 233, DateTimeKind.Local).AddTicks(5968)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.Address", b =>
                {
                    b.HasOne("ECommerce.Entities.Concrete.Identity.Entities.AppUser", "AppUser")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.Brand", b =>
                {
                    b.HasOne("ECommerce.Entities.Concrete.SubCategory", "SubCategory")
                        .WithMany("Brands")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.Model", b =>
                {
                    b.HasOne("ECommerce.Entities.Concrete.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Entities.Concrete.Ad", "Ad")
                        .WithOne("Model")
                        .HasForeignKey("ECommerce.Entities.Concrete.Model", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ad");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.SubCategory", b =>
                {
                    b.HasOne("ECommerce.Entities.Concrete.MainCategory", "MainCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("MainCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.UserImage", b =>
                {
                    b.HasOne("ECommerce.Entities.Concrete.Identity.Entities.AppUser", "AppUser")
                        .WithMany("UserImages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.VehicleAddress", b =>
                {
                    b.HasOne("ECommerce.Entities.Concrete.Ad", "Ad")
                        .WithOne("VehicleAddress")
                        .HasForeignKey("ECommerce.Entities.Concrete.VehicleAddress", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ad");
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.VehicleImage", b =>
                {
                    b.HasOne("ECommerce.Entities.Concrete.Ad", "Ad")
                        .WithMany("VehicleImages")
                        .HasForeignKey("AdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("ECommerce.Entities.Concrete.Identity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ECommerce.Entities.Concrete.Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ECommerce.Entities.Concrete.Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("ECommerce.Entities.Concrete.Identity.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Entities.Concrete.Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ECommerce.Entities.Concrete.Identity.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.Ad", b =>
                {
                    b.Navigation("Model");

                    b.Navigation("VehicleAddress");

                    b.Navigation("VehicleImages");
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.Identity.Entities.AppUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("UserImages");
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.MainCategory", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ECommerce.Entities.Concrete.SubCategory", b =>
                {
                    b.Navigation("Brands");
                });
#pragma warning restore 612, 618
        }
    }
}
